AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stage 4e: Auto Scaling for ECS Services'

Parameters:
  ProjectName:
    Type: String
    Default: 'aqua-sample-apps'
  
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']
  
  FrontendMinCapacity:
    Type: Number
    Default: 2
  
  FrontendMaxCapacity:
    Type: Number
    Default: 10
  
  BackendMinCapacity:
    Type: Number
    Default: 2
  
  BackendMaxCapacity:
    Type: Number
    Default: 10
  
  TargetCPUUtilization:
    Type: Number
    Default: 70
  
  TargetMemoryUtilization:
    Type: Number
    Default: 80

Resources:
  # Frontend Auto Scaling
  FrontendScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      ServiceNamespace: ecs
      ResourceId: !Sub 
        - 'service/${ClusterName}/${ServiceName}'
        - ClusterName:
            Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ClusterName'
          ServiceName:
            Fn::ImportValue: !Sub '${ProjectName}-${Environment}-FrontendServiceName'
      ScalableDimension: ecs:service:DesiredCount
      MinCapacity: !Ref FrontendMinCapacity
      MaxCapacity: !Ref FrontendMaxCapacity
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService'

  FrontendCPUScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${ProjectName}-${Environment}-frontend-cpu-scaling'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref FrontendScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: !Ref TargetCPUUtilization
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 300
        ScaleOutCooldown: 60

  FrontendMemoryScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${ProjectName}-${Environment}-frontend-memory-scaling'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref FrontendScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: !Ref TargetMemoryUtilization
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageMemoryUtilization
        ScaleInCooldown: 300
        ScaleOutCooldown: 60

  # Backend Auto Scaling
  BackendScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      ServiceNamespace: ecs
      ResourceId: !Sub 
        - 'service/${ClusterName}/${ServiceName}'
        - ClusterName:
            Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ClusterName'
          ServiceName:
            Fn::ImportValue: !Sub '${ProjectName}-${Environment}-BackendServiceName'
      ScalableDimension: ecs:service:DesiredCount
      MinCapacity: !Ref BackendMinCapacity
      MaxCapacity: !Ref BackendMaxCapacity
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService'

  BackendCPUScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${ProjectName}-${Environment}-backend-cpu-scaling'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref BackendScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: !Ref TargetCPUUtilization
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 300
        ScaleOutCooldown: 60

  BackendMemoryScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${ProjectName}-${Environment}-backend-memory-scaling'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref BackendScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        TargetValue: !Ref TargetMemoryUtilization
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageMemoryUtilization
        ScaleInCooldown: 300
        ScaleOutCooldown: 60

Outputs:
  FrontendScalableTargetId:
    Description: Frontend Scalable Target ID
    Value: !Ref FrontendScalableTarget

  BackendScalableTargetId:
    Description: Backend Scalable Target ID
    Value: !Ref BackendScalableTarget