AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stage 4.6: Simplified ECS Services with Debug-Friendly Configuration'

Parameters:
  ProjectName:
    Type: String
    Default: 'aqua-sample-app'
  
  Environment:
    Type: String
    Default: 'production'
  
  VpcId:
    Type: AWS::EC2::VPC::Id
  
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
  
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
  
  FrontendDesiredCount:
    Type: Number
    Default: 1
    MinValue: 0
    MaxValue: 10
    Description: 'Start with 1 for easier debugging'
  
  BackendDesiredCount:
    Type: Number
    Default: 1
    MinValue: 0
    MaxValue: 10
    Description: 'Start with 1 for easier debugging'

Resources:
  # ============================================
  # FRONTEND SERVICE - SIMPLIFIED
  # ============================================
  FrontendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${ProjectName}-${Environment}-frontend-svc'
      Cluster:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ClusterName'
      TaskDefinition:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-FrontendTaskDefArn'
      
      # Start with minimal count
      DesiredCount: !Ref FrontendDesiredCount
      
      # Use FARGATE for simplicity
      LaunchType: FARGATE
      PlatformVersion: LATEST
      
      # Network configuration
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ECSSecurityGroupId'
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
      
      # Load balancer configuration
      LoadBalancers:
        - ContainerName: frontend
          ContainerPort: 8080
          TargetGroupArn:
            Fn::ImportValue: !Sub '${ProjectName}-${Environment}-FrontendTGArn'
      
      # Service discovery (optional - can be removed if causing issues)
      ServiceRegistries:
        - RegistryArn:
            Fn::ImportValue: !Sub '${ProjectName}-${Environment}-FrontendSDArn'
      
      # Deployment configuration - VERY LENIENT for debugging
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 0  # Allow all tasks to be replaced
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: false  # Don't auto-rollback so we can debug
      
      # Enable ECS Exec for debugging
      EnableExecuteCommand: true
      
      # IMPORTANT: Longer grace period for health checks
      HealthCheckGracePeriodSeconds: 300  # 5 minutes
      
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-frontend-svc'
        - Key: Environment
          Value: !Ref Environment

  # ============================================
  # BACKEND SERVICE - SIMPLIFIED
  # ============================================
  BackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${ProjectName}-${Environment}-backend-svc'
      Cluster:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ClusterName'
      TaskDefinition:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-BackendTaskDefArn'
      
      # Start with minimal count
      DesiredCount: !Ref BackendDesiredCount
      
      # Use FARGATE for simplicity
      LaunchType: FARGATE
      PlatformVersion: LATEST
      
      # Network configuration
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ECSSecurityGroupId'
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
      
      # Load balancer configuration
      LoadBalancers:
        - ContainerName: backend
          ContainerPort: 3000
          TargetGroupArn:
            Fn::ImportValue: !Sub '${ProjectName}-${Environment}-BackendTGArn'
      
      # Service discovery (optional)
      ServiceRegistries:
        - RegistryArn:
            Fn::ImportValue: !Sub '${ProjectName}-${Environment}-BackendSDArn'
      
      # Deployment configuration - VERY LENIENT
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 0
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: false
      
      # Enable ECS Exec for debugging
      EnableExecuteCommand: true
      
      # Longer grace period
      HealthCheckGracePeriodSeconds: 300  # 5 minutes
      
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-backend-svc'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  FrontendServiceArn:
    Description: Frontend Service ARN
    Value: !Ref FrontendService
    Export:
      Name: !Sub '${ProjectName}-${Environment}-FrontendServiceArn'

  FrontendServiceName:
    Description: Frontend Service Name
    Value: !GetAtt FrontendService.Name
    Export:
      Name: !Sub '${ProjectName}-${Environment}-FrontendServiceName'

  BackendServiceArn:
    Description: Backend Service ARN
    Value: !Ref BackendService
    Export:
      Name: !Sub '${ProjectName}-${Environment}-BackendServiceArn'

  BackendServiceName:
    Description: Backend Service Name
    Value: !GetAtt BackendService.Name
    Export:
      Name: !Sub '${ProjectName}-${Environment}-BackendServiceName'