AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stage 4.4b: CodePipeline for Initial Deployment from GitHub'

Parameters:
  ProjectName:
    Type: String
    Default: 'aqua-sample-app'
  
  Environment:
    Type: String
    Default: 'production'
  
  GitHubConnectionArn:
    Type: String
    Description: 'GitHub Connection ARN from CodeStar Connections'
  
  GitHubRepoFrontend:
    Type: String
    Default: 'aqua-vietnam/sample_frontend-repo'
  
  GitHubRepoBackend:
    Type: String
    Default: 'aqua-vietnam/sample_backend-repo'
  
  GitHubBranch:
    Type: String
    Default: 'main'
    Description: 'Branch to deploy (main or master)'

Resources:
  # ============================================
  # FRONTEND PIPELINE
  # ============================================
  FrontendPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-frontend-pipeline'
      RoleArn:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-CodePipelineRoleArn'
      
      ArtifactStore:
        Type: S3
        Location:
          Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ArtifactsBucket'
      
      Stages:
        # ============================================
        # STAGE 1: SOURCE
        # ============================================
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: !Ref GitHubRepoFrontend
                BranchName: !Ref GitHubBranch
                OutputArtifactFormat: CODE_ZIP
                DetectChanges: false
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
        
        # ============================================
        # STAGE 2: BUILD
        # ============================================
        - Name: Build
          Actions:
            - Name: DockerBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName:
                  Fn::ImportValue: !Sub '${ProjectName}-${Environment}-PipelineFrontendBuildName'
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
        
        # ============================================
        # STAGE 3: DEPLOY (Will be added after ECS services are created)
        # ============================================
        # Commented out for now - will enable after Step 4.6
        # - Name: Deploy
        #   Actions:
        #     - Name: DeployToECS
        #       ActionTypeId:
        #         Category: Deploy
        #         Owner: AWS
        #         Provider: ECS
        #         Version: '1'
        #       Configuration:
        #         ClusterName:
        #           Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ClusterName'
        #         ServiceName:
        #           Fn::ImportValue: !Sub '${ProjectName}-${Environment}-FrontendServiceName'
        #         FileName: imagedefinitions.json
        #         DeploymentTimeout: 15
        #       InputArtifacts:
        #         - Name: BuildArtifact
        #       RunOrder: 1
      
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-frontend-pipeline'
        - Key: Environment
          Value: !Ref Environment

  # ============================================
  # BACKEND PIPELINE
  # ============================================
  BackendPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-backend-pipeline'
      RoleArn:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-CodePipelineRoleArn'
      
      ArtifactStore:
        Type: S3
        Location:
          Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ArtifactsBucket'
      
      Stages:
        # ============================================
        # STAGE 1: SOURCE
        # ============================================
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref GitHubConnectionArn
                FullRepositoryId: !Ref GitHubRepoBackend
                BranchName: !Ref GitHubBranch
                OutputArtifactFormat: CODE_ZIP
                DetectChanges: false
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
        
        # ============================================
        # STAGE 2: BUILD
        # ============================================
        - Name: Build
          Actions:
            - Name: DockerBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName:
                  Fn::ImportValue: !Sub '${ProjectName}-${Environment}-PipelineBackendBuildName'
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
        
        # ============================================
        # STAGE 3: DEPLOY (Will be added after ECS services are created)
        # ============================================
        # Commented out for now - will enable after Step 4.6
        # - Name: Deploy
        #   Actions:
        #     - Name: DeployToECS
        #       ActionTypeId:
        #         Category: Deploy
        #         Owner: AWS
        #         Provider: ECS
        #         Version: '1'
        #       Configuration:
        #         ClusterName:
        #           Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ClusterName'
        #         ServiceName:
        #           Fn::ImportValue: !Sub '${ProjectName}-${Environment}-BackendServiceName'
        #         FileName: imagedefinitions.json
        #         DeploymentTimeout: 15
        #       InputArtifacts:
        #         - Name: BuildArtifact
        #       RunOrder: 1
      
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-backend-pipeline'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  FrontendPipelineName:
    Description: Frontend Pipeline Name
    Value: !Ref FrontendPipeline
    Export:
      Name: !Sub '${ProjectName}-${Environment}-FrontendPipelineName'

  BackendPipelineName:
    Description: Backend Pipeline Name
    Value: !Ref BackendPipeline
    Export:
      Name: !Sub '${ProjectName}-${Environment}-BackendPipelineName'

  FrontendPipelineArn:
    Description: Frontend Pipeline ARN
    Value: !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${FrontendPipeline}'

  BackendPipelineArn:
    Description: Backend Pipeline ARN
    Value: !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${BackendPipeline}'