AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stage 4c: ECS Task Definitions'

Parameters:
  ProjectName:
    Type: String
    Default: 'aqua-sample-app'
  
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']
  
  FrontendCPU:
    Type: String
    Default: '256'
    AllowedValues: ['256', '512', '1024', '2048']
  
  FrontendMemory:
    Type: String
    Default: '512'
    AllowedValues: ['512', '1024', '2048', '4096']
  
  BackendCPU:
    Type: String
    Default: '512'
    AllowedValues: ['256', '512', '1024', '2048']
  
  BackendMemory:
    Type: String
    Default: '1024'
    AllowedValues: ['512', '1024', '2048', '4096']

Resources:
  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${ProjectName}-${Environment}-frontend'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref FrontendCPU
      Memory: !Ref FrontendMemory
      ExecutionRoleArn:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ECSTaskExecRoleArn'
      TaskRoleArn:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ECSTaskRoleArn'
      ContainerDefinitions:
        - Name: frontend
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}-${Environment}-frontend:latest'
          Essential: true
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: !Ref Environment
            - Name: API_URL
              Value: !Sub 'http://backend.${ProjectName}-${Environment}.local:8080'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Fn::ImportValue: !Sub '${ProjectName}-${Environment}-FrontendLogGroup'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:3000/ || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-frontend-task'
        - Key: Environment
          Value: !Ref Environment

  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${ProjectName}-${Environment}-backend'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref BackendCPU
      Memory: !Ref BackendMemory
      ExecutionRoleArn:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ECSTaskExecRoleArn'
      TaskRoleArn:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ECSTaskRoleArn'
      ContainerDefinitions:
        - Name: backend
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ProjectName}-${Environment}-backend:latest'
          Essential: true
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: !Ref Environment
            - Name: PORT
              Value: '8080'
          Secrets:
            - Name: DATABASE_URL
              ValueFrom:
                Fn::ImportValue: !Sub '${ProjectName}-${Environment}-DatabaseSecretArn'
            - Name: API_KEY
              ValueFrom:
                Fn::ImportValue: !Sub '${ProjectName}-${Environment}-APIKeySecretArn'
            - Name: JWT_SECRET
              ValueFrom:
                Fn::ImportValue: !Sub '${ProjectName}-${Environment}-JWTSecretArn'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Fn::ImportValue: !Sub '${ProjectName}-${Environment}-BackendLogGroup'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:8080/health || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-backend-task'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  FrontendTaskDefinitionArn:
    Description: Frontend Task Definition ARN
    Value: !Ref FrontendTaskDefinition
    Export:
      Name: !Sub '${ProjectName}-${Environment}-FrontendTaskDefArn'

  BackendTaskDefinitionArn:
    Description: Backend Task Definition ARN
    Value: !Ref BackendTaskDefinition
    Export:
      Name: !Sub '${ProjectName}-${Environment}-BackendTaskDefArn'