AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stage 1b: CloudWatch Log Groups'

Parameters:
  ProjectName:
    Type: String
    Description: Project name for resource naming
    Default: 'aqua-sample-app'
  
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']

Conditions:
  IsProduction: !Equals [!Ref Environment, 'production']

Resources:
  # ============================================
  # ECS LOG GROUPS
  # ============================================
  FrontendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}-${Environment}/frontend'
      RetentionInDays: !If [IsProduction, 30, 7]
      KmsKeyId:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-CloudWatchKMSKeyArn'

  BackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}-${Environment}/backend'
      RetentionInDays: !If [IsProduction, 30, 7]
      KmsKeyId:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-CloudWatchKMSKeyArn'

  # ============================================
  # ECS EXEC LOG GROUP
  # ============================================
  ECSExecLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}-${Environment}/exec'
      RetentionInDays: !If [IsProduction, 30, 7]
      KmsKeyId:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-CloudWatchKMSKeyArn'

  # ============================================
  # CODEBUILD LOG GROUPS
  # ============================================
  FrontendBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/codebuild/${ProjectName}-${Environment}-frontend'
      RetentionInDays: !If [IsProduction, 14, 7]

  BackendBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/codebuild/${ProjectName}-${Environment}-backend'
      RetentionInDays: !If [IsProduction, 14, 7]

  InitFrontendBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/codebuild/${ProjectName}-${Environment}-init-frontend'
      RetentionInDays: 7

  InitBackendBuildLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/codebuild/${ProjectName}-${Environment}-init-backend'
      RetentionInDays: 7

  # ============================================
  # LAMBDA LOG GROUPS
  # ============================================
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-InitialBuildTrigger'
      RetentionInDays: 7

Outputs:
  FrontendLogGroupName:
    Description: Frontend Log Group Name
    Value: !Ref FrontendLogGroup
    Export:
      Name: !Sub '${ProjectName}-${Environment}-FrontendLogGroup'

  BackendLogGroupName:
    Description: Backend Log Group Name
    Value: !Ref BackendLogGroup
    Export:
      Name: !Sub '${ProjectName}-${Environment}-BackendLogGroup'

  ECSExecLogGroupName:
    Description: ECS Exec Log Group Name
    Value: !Ref ECSExecLogGroup
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ECSExecLogGroup'

  FrontendBuildLogGroupName:
    Description: Frontend Build Log Group Name
    Value: !Ref FrontendBuildLogGroup
    Export:
      Name: !Sub '${ProjectName}-${Environment}-FrontendBuildLogGroup'

  BackendBuildLogGroupName:
    Description: Backend Build Log Group Name
    Value: !Ref BackendBuildLogGroup
    Export:
      Name: !Sub '${ProjectName}-${Environment}-BackendBuildLogGroup'