AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stage 2b: Secrets Manager - Placeholders for application secrets'

Parameters:
  ProjectName:
    Type: String
    Default: 'aqua-sample-app'
  
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']

Resources:
  # ============================================
  # DATABASE SECRET
  # ============================================
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}-${Environment}/database/url'
      Description: Database connection URL
      SecretString: 'PLACEHOLDER-UPDATE-THIS-VALUE'
      KmsKeyId:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ECRKMSKeyArn'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-db-secret'
        - Key: Environment
          Value: !Ref Environment

  # ============================================
  # API KEY SECRET
  # ============================================
  APIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}-${Environment}/api/key'
      Description: API Key for external services
      SecretString: 'PLACEHOLDER-UPDATE-THIS-VALUE'
      KmsKeyId:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ECRKMSKeyArn'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-api-secret'
        - Key: Environment
          Value: !Ref Environment

  # ============================================
  # JWT SECRET
  # ============================================
  JWTSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}-${Environment}/jwt/secret'
      Description: JWT signing secret
      SecretString: 'PLACEHOLDER-UPDATE-THIS-VALUE'
      KmsKeyId:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ECRKMSKeyArn'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-jwt-secret'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  DatabaseSecretArn:
    Description: Database Secret ARN
    Value: !Ref DatabaseSecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-DatabaseSecretArn'

  APIKeySecretArn:
    Description: API Key Secret ARN
    Value: !Ref APIKeySecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-APIKeySecretArn'

  JWTSecretArn:
    Description: JWT Secret ARN
    Value: !Ref JWTSecret
    Export:
      Name: !Sub '${ProjectName}-${Environment}-JWTSecretArn'