AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stage 3b: S3 Buckets with Complete ELB Logging Support'

Parameters:
  ProjectName:
    Type: String
    Default: 'aqua-sample-app'
  
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']

Conditions:
  IsProduction: !Equals [!Ref Environment, 'production']

Resources:
  # ============================================
  # ARTIFACTS BUCKET (WITH KMS)
  # ============================================
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-artifacts-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID:
                Fn::ImportValue: !Sub '${ProjectName}-${Environment}-S3KMSKeyArn'
            BucketKeyEnabled: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: !If [IsProduction, 90, 30]
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: !If [IsProduction, 90, 30]
                StorageClass: STANDARD_IA
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-artifacts'
        - Key: Environment
          Value: !Ref Environment

  ArtifactsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactsBucket
      PolicyDocument:
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt ArtifactsBucket.Arn
              - !Sub '${ArtifactsBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': false

  # ============================================
  # LOGS BUCKET (SERVER-SIDE ENCRYPTION ONLY - NO KMS)
  # This is the recommended approach for ALB logs
  # ============================================
  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-logs-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256  # SSE-S3 instead of KMS for ALB compatibility
      LifecycleConfiguration:
        Rules:
          - Id: ExpireLogs
            Status: Enabled
            ExpirationInDays: !If [IsProduction, 90, 30]
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-logs'
        - Key: Environment
          Value: !Ref Environment

  LogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureTransport
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !GetAtt LogsBucket.Arn
              - !Sub '${LogsBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': false
          
          # Allow ELB service to write logs
          - Sid: AllowELBServiceAccount
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::114774131450:root'
            Action: 's3:PutObject'
            Resource: !Sub '${LogsBucket.Arn}/*'
          
          # Allow ELB to check bucket ACL
          - Sid: AllowELBServiceAccountGetAcl
            Effect: Allow
            Principal:
              AWS: 'arn:aws:iam::114774131450:root'
            Action: 's3:GetBucketAcl'
            Resource: !GetAtt LogsBucket.Arn

Outputs:
  ArtifactsBucketName:
    Description: Artifacts Bucket Name
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ArtifactsBucket'

  ArtifactsBucketArn:
    Description: Artifacts Bucket ARN
    Value: !GetAtt ArtifactsBucket.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ArtifactsBucketArn'

  LogsBucketName:
    Description: Logs Bucket Name
    Value: !Ref LogsBucket
    Export:
      Name: !Sub '${ProjectName}-${Environment}-LogsBucket'
  
  LogsBucketArn:
    Description: Logs Bucket ARN
    Value: !GetAtt LogsBucket.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-LogsBucketArn'