AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stage 3e: WAF for Application Load Balancer'

Parameters:
  ProjectName:
    Type: String
    Default: 'aqua-sample-app'
  
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']
  
  RateLimitPerIP:
    Type: Number
    Default: 2000
    Description: Max requests per 5 minutes from single IP

Resources:
  WAFWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-WAF'
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      Rules:
        - Name: RateLimitRule
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: !Ref RateLimitPerIP
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule
        
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: CommonRuleSet
        
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: KnownBadInputs
        
        - Name: AWSManagedRulesSQLiRuleSet
          Priority: 4
          OverrideAction:
            None: {}
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: SQLiRuleSet
      
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub '${ProjectName}-${Environment}-WAF'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-WAF'
        - Key: Environment
          Value: !Ref Environment

  WAFAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-ALBArn'
      WebACLArn: !GetAtt WAFWebACL.Arn

Outputs:
  WAFWebACLArn:
    Description: WAF Web ACL ARN
    Value: !GetAtt WAFWebACL.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-WAFArn'

  WAFWebACLId:
    Description: WAF Web ACL ID
    Value: !GetAtt WAFWebACL.Id
    Export:
      Name: !Sub '${ProjectName}-${Environment}-WAFId'