AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stage 5c: Initial Image Builders (Lambda + CodeBuild)'

Parameters:
  ProjectName:
    Type: String
    Default: 'myproject'
  
  Environment:
    Type: String
    Default: 'production'
    AllowedValues: ['development', 'staging', 'production']

Resources:
  InitFrontendBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-init-frontend'
      Description: Initial build for frontend placeholder image
      ServiceRole:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-CodeBuildRoleArn'
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: IMAGE_REPO_NAME
            Value: !Sub '${ProjectName}-${Environment}-frontend'
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - echo Logging in to Amazon ECR...
                - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
            build:
              commands:
                - echo Building placeholder frontend image...
                - |
                  cat > Dockerfile <<EOF
                  FROM nginx:alpine
                  RUN echo '<h1>Frontend Placeholder</h1>' > /usr/share/nginx/html/index.html
                  EXPOSE 3000
                  CMD ["nginx", "-g", "daemon off;"]
                  EOF
                - docker build -t $IMAGE_REPO_NAME:latest .
                - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
            post_build:
              commands:
                - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
                - echo Placeholder image pushed successfully
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-init-frontend'

  InitBackendBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub '${ProjectName}-${Environment}-init-backend'
      Description: Initial build for backend placeholder image
      ServiceRole:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-CodeBuildRoleArn'
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: IMAGE_REPO_NAME
            Value: !Sub '${ProjectName}-${Environment}-backend'
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - echo Logging in to Amazon ECR...
                - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
            build:
              commands:
                - echo Building placeholder backend image...
                - |
                  cat > Dockerfile <<EOF
                  FROM node:18-alpine
                  WORKDIR /app
                  RUN echo 'const express = require("express"); const app = express(); app.get("/health", (req, res) => res.json({status: "ok"})); app.listen(8080);' > server.js
                  RUN npm init -y && npm install express
                  EXPOSE 8080
                  CMD ["node", "server.js"]
                  EOF
                - docker build -t $IMAGE_REPO_NAME:latest .
                - docker tag $IMAGE_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
            post_build:
              commands:
                - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-init-backend'

  TriggerLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-${Environment}-InitialBuildTrigger'
      Runtime: python3.11
      Handler: index.lambda_handler
      Role:
        Fn::ImportValue: !Sub '${ProjectName}-${Environment}-LambdaExecRoleArn'
      Timeout: 300
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          
          codebuild = boto3.client('codebuild')
          
          def lambda_handler(event, context):
              try:
                  if event['RequestType'] == 'Create':
                      frontend_project = event['ResourceProperties']['FrontendProject']
                      backend_project = event['ResourceProperties']['BackendProject']
                      
                      codebuild.start_build(projectName=frontend_project)
                      codebuild.start_build(projectName=backend_project)
                      
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                  else:
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                  print(f"Error: {str(e)}")
                  cfnresponse.send(event, context, cfnresponse.FAILED, {})
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-InitialBuildTrigger'

  TriggerInitialBuilds:
    Type: Custom::TriggerBuilds
    Properties:
      ServiceToken: !GetAtt TriggerLambdaFunction.Arn
      FrontendProject: !Ref InitFrontendBuildProject
      BackendProject: !Ref InitBackendBuildProject

Outputs:
  InitFrontendBuildProjectArn:
    Description: Init Frontend Build Project ARN
    Value: !GetAtt InitFrontendBuildProject.Arn

  InitBackendBuildProjectArn:
    Description: Init Backend Build Project ARN
    Value: !GetAtt InitBackendBuildProject.Arn